apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mcdemos.operator.demo
spec:
  group: operator.demo
  names:
    kind: MCDemo
    listKind: MCDemoList
    plural: mcdemos
    singular: mcdemo
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
